POST http://localhost:5119/Question/ask
Content-Type: application/json

{
  "question": "det sanna värdet"
}

###

POST https://localhost:7233/Question/ask
Content-Type: application/json

{
  "question": "det sanna värdet"
}
